// This file is autogenerated by the add-lucide-icons script.
// Do not edit this file manually.

export {
  Book,
  Brush,
  ShieldCheck,
  Star,
  Trophy,
  Zap,
  Swords,
  Mountain,
  Flower,
  Gem,
  Bug,
  Pause,
  Play,
  Info,
  Pencil,
  Check,
  Timer,
  RotateCcw,
  Settings2,
} from 'lucide-react';
